### ISSUE TITLE
Failed to start Spark 3.1 with error msg 'Cannot modify the value of a Spark config'

### ISSUE THREAD

**Issue by ulysses-you** [yaooqinn/kyuubi#410]
**Describe the bug**
```
Caused by: org.apache.spark.sql.AnalysisException: Cannot modify the value of a Spark config: spark.yarn.queue
	at org.apache.spark.sql.RuntimeConfig.requireNonStaticConf(RuntimeConfig.scala:156)
	at org.apache.spark.sql.RuntimeConfig.set(RuntimeConfig.scala:40)
	at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager.$anonfun$openSession$2(SparkSQLSessionManager.scala:68)
	at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager.$anonfun$openSession$2$adapted(SparkSQLSessionManager.scala:56)
	at scala.collection.immutable.Map$Map4.foreach(Map.scala:236)
	at org.apache.kyuubi.engine.spark.session.SparkSQLSessionManager.openSession(SparkSQLSessionManager.scala:56)
	... 12 more
```

Kyuubi should not pass the unused config to Spark.

For now the exception could be skipped by `spark.sql.legacy.setCommandRejectsSparkCoreConfs=false`.

**To Reproduce**
1. Use beeline to create connection with Kyuubi.
2. Get such exception

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ulysses-you** [comment]
Add the trouble shooting firstly. https://github.com/yaooqinn/kyuubi/pull/409

Then we need to skip the unused config before pass to SparkConf.

**Comment by yaooqinn** [comment]
Currently, we don't distinguish these configs at all. If a Kyuubi Spark SQL engine needs to bootstrap, all of them will be get prefixed w/ `spark.`, as the `spark-submit`  only accepts configs in such a pattern. For example,  if there is `key1=value1` in `#<[spark|hive]Vars>` part, it will become `--conf spark.key1=value1` during engine bootstrapping and stay as `key1=value1` while setting up the connection with the engine. The former is unnecessary and could mistakenly override the actual `spark.key1=othervalue` in the other configuration part.

> > dismissed if engine exists.
> 
> is this the major change you want to propose?

This is the expected behavior as it is now but breaks in Spark 3.1.1. The problem seems to be that we call Spark's internal/unstable API, which we shall avoid.

```SparkSession.sql("set ...")``` might be a better choice.

Handling configurations properly in Kyuubi ahead and not relying on Spark's behavior too much is also a good way to go.

**Comment by pan3793** [comment]
> Runtime SQL Configuration
> Also, they can be set and queried by SET commands and rest to their initial values by RESET command

So we can use `[spark|hive]Vars` to overwrite `sessionConfs`?

**Comment by yaooqinn** [comment]
> > Runtime SQL Configuration
> > Also, they can be set and queried by SET commands and rest to their initial values by RESET command
> 
> So we can use `[spark|hive]Vars` to overwrite `sessionConfs`?
> 
> If yes, it's better to clarify the priority of those configs

yea, simply latecomer first
